server:
  port: 8084
spring:
  thymeleaf:
    cache: false
  application:
    name: page-service
  rabbitmq:
    host: 192.168.13.111
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  static:
    itemDir: D:\\leyou-code\\326127\\software\\nginx-1.16.0\\html\\item
    templateName: item