server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.13.111
    virtual-host: /leyou
    username: leyou
    password: leyou
ly:
  sms:
    accessKeyID: LTAI4FdkwsDcqJKM9PiAudW4 # 你自己的accessKeyId
    accessKeySecret: uS8OrKYZ5XJnXBCSeXltcowrajzXrC # 你自己的AccessKeySecret
    signName: 乐优 # 签名名称
    verifyCodeTemplate: SMS_181196148 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id