server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    root: info
    com.leyou: debug
ly:
  jwt:
    pubKeyPath: D:/leyou-code/326127/rsa/id_rsa.pub # 公钥地址
    priKeyPath: D:/leyou-code/326127/rsa/id_rsa # 私钥地址
    user:
      expire: 30 #过期时间设置
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域

