server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # 添加cors的解决方案
      globalcors:
        add-to-simple-url-handler-mapping: true  # 预检请求; 特殊请求
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://manage.leyou.com"
              - "http://www.leyou.com"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 360000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - HEAD
      # 路由配置
      routes:
        - id: item-service        # id，可以随便定义
          uri: lb://item-service  # 后面的是微服务的id，不能乱写
          predicates:
            - Path=/api/item/**   # 路由断言映射
          filters:
            - StripPrefix=2       # 代表去除 api的前缀
        - id: upload-service        # id，可以随便定义
          uri: lb://upload-service  # 后面的是微服务的id，不能乱写
          predicates:
            - Path=/api/upload/**   # 路由断言映射
          filters:
            - StripPrefix=2       # 代表去除 api的前缀
        - id: search-service    #搜索微服务
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=2
        - id: user-service    #用户微服务
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: auth-service    #授权微服务
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试


ly:
  jwt:
    pubKeyPath: D:/leyou-code/326127/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
    app:
      id: 7
      secret: api-gateway # $2a$10$iW4/EHiMFSew/5GmEPyoi.B40Q5gMCFGoTYykyn0ZAe5XoFzNy7O.
      headerName: privilege_token
  filter:
    allowPaths:   #过滤器中的白名单设置
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      #- /api/item  # 我们现在把这里注释掉，演示黑客绕开网关