server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.111:3306/leyou?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
  rabbitmq:
    host: 192.168.13.111
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000  #第一次重试的间隔时间
        max-attempts: 3 #最多重试的次数
        max-interval: 80000 # 最大的重试的时间
        multiplier: 2 # 下一次重试间隔时间的倍数
    publisher-confirms: true   # RabbitMQ服务接收到消息之后 给生产者确认消息，如果没有响应，才会重试
  main:
    allow-bean-definition-overriding: true  # 如果spring容器中出现了相同的bean，我们可以替换
mybatis:
    type-aliases-package: com.leyou.item.entity
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations: mapper/*.xml
mapper:
  wrap-keyword: "`{0}`"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    root: info
    com.leyou: debug

